/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;



/**
 *
 * @author thiag
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpcapa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cranimal = new javax.swing.JMenuItem();
        crcliente = new javax.swing.JMenuItem();
        crfuncionario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        rlanimal = new javax.swing.JMenuItem();
        rlfuncionario = new javax.swing.JMenuItem();
        rladocao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));

        jpcapa.setBackground(new java.awt.Color(200, 162, 200));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo_2.PNG"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setFocusable(false);

        javax.swing.GroupLayout jpcapaLayout = new javax.swing.GroupLayout(jpcapa);
        jpcapa.setLayout(jpcapaLayout);
        jpcapaLayout.setHorizontalGroup(
            jpcapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
        );
        jpcapaLayout.setVerticalGroup(
            jpcapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpcapaLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Cadastro");

        cranimal.setText("Cadastro de Animal");
        cranimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cranimalActionPerformed(evt);
            }
        });
        jMenu1.add(cranimal);

        crcliente.setText("Cadastro de Cliente");
        crcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crclienteActionPerformed(evt);
            }
        });
        jMenu1.add(crcliente);

        crfuncionario.setText("Cadastro de Funcionario");
        crfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crfuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(crfuncionario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatorio");

        rlanimal.setText("Relatorio de Animais");
        rlanimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rlanimalActionPerformed(evt);
            }
        });
        jMenu2.add(rlanimal);

        rlfuncionario.setText("Relatorio de Funcionarios");
        rlfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rlfuncionarioActionPerformed(evt);
            }
        });
        jMenu2.add(rlfuncionario);

        rladocao.setText("Relatorio de Adoções");
        rladocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rladocaoActionPerformed(evt);
            }
        });
        jMenu2.add(rladocao);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpcapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpcapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cranimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cranimalActionPerformed
        new FrAnimal().setVisible(true);
    }//GEN-LAST:event_cranimalActionPerformed

    private void crclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crclienteActionPerformed
        // TODO add your handling code here:
        new FrCliente().setVisible(true);
    }//GEN-LAST:event_crclienteActionPerformed

    private void rlanimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rlanimalActionPerformed
        
        new RelAnimal().setVisible(true);
        
    }//GEN-LAST:event_rlanimalActionPerformed

    private void crfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crfuncionarioActionPerformed
        
        new FrFuncionario().setVisible(true);
        
    }//GEN-LAST:event_crfuncionarioActionPerformed

    private void rlfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rlfuncionarioActionPerformed
        
        new RelFuncionario().setVisible(true);
    }//GEN-LAST:event_rlfuncionarioActionPerformed

    private void rladocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rladocaoActionPerformed
        
        new RelAdocao().setVisible(true);
        
    }//GEN-LAST:event_rladocaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cranimal;
    private javax.swing.JMenuItem crcliente;
    private javax.swing.JMenuItem crfuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jpcapa;
    private javax.swing.JMenuItem rladocao;
    private javax.swing.JMenuItem rlanimal;
    private javax.swing.JMenuItem rlfuncionario;
    // End of variables declaration//GEN-END:variables
}
