/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import classe.Animal;
import classe.Cliente;
import classe.Funcionario;
import dao.AnimalDao;
import dao.ClienteDao;
import dao.FuncionarioDao;
import classe.Adocao;
import dao.AdocaoDao;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 62127512022.2
 */
public class RelAdocao extends javax.swing.JFrame {

    Cliente cliente = new Cliente();
    ClienteDao cdao = new ClienteDao();
    Funcionario funcionario = new Funcionario();
    FuncionarioDao fdao = new FuncionarioDao();
    Animal animal = new Animal();
    AnimalDao adao = new AnimalDao();
    Adocao adocao = new Adocao();
    AdocaoDao adocaodao = new AdocaoDao();
    
    Date Data1;
    String data1 = null;
    
    
    public RelAdocao() {
        initComponents();
        ptabela.setVisible(false);
        btatualiza.setVisible(false);
        mostratabela();
        txdata.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis())));
        preenchecombo();
        
    }
    
    private void preenchecombo(){
          
            List<Cliente> clientes = cdao.BuscaClientes();
            
            for(Cliente cliente : clientes){
                
                cbcliente.addItem(cliente.getNome());
                
            }
            
        
            
            List<Funcionario> funcionarios = fdao.BuscaFuncionarios();
            
            for(Funcionario funcionario : funcionarios){
                
                cbfuncionario.addItem(funcionario.getNome());
                
            }
            
            List<Animal> animais = adao.BuscaAnimais();
            
            for(Animal animal : animais){
                
                cbanimal.addItem(animal.getNome());
                
            }
           
    }
    
    private void passadados(){
       
       //Animal
       animal.setNome(String.valueOf(cbanimal.getSelectedItem()));
       adao.Buscanome(animal);
       adocao.setIdanimal(animal.getIdanimal()); 

        
       //Cliente 
       cliente.setNome(String.valueOf(cbcliente.getSelectedItem()));
       cdao.buscaClienteNome(cliente);
       adocao.setIdcliente(cliente.getIdCliente());
       
       
       //Funcionario
       funcionario.setNome(String.valueOf(cbfuncionario.getSelectedItem()));
       fdao.buscarFuncionario(funcionario);
       adocao.setIdfuncionario(funcionario.getIdfuncionario());
       
       
       
       
       //Formatação data
        
       try { 
            
            Data1 = new SimpleDateFormat("dd/MM/yyyy").parse(txdata.getText());
        
        } 
        
        catch (ParseException ex) {
            
            Logger.getLogger(RelAdocao.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        data1 = new SimpleDateFormat("yyyy-MM-dd").format(Data1);
        adocao.setData(data1);
        
    }
    
    public void mostratabela(){
        tbadocao.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbadocao.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbadocao.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbadocao.getColumnModel().getColumn(3).setPreferredWidth(100);
        tbadocao.getColumnModel().getColumn(4).setPreferredWidth(100);
        
        DefaultTableModel modelo = (DefaultTableModel)tbadocao.getModel();
            modelo.setNumRows(0);
            
            
            
            List<Adocao> adocoes = adocaodao.ListaAdocao();
            
            for(Adocao adocao : adocoes){
                
                modelo.addRow(new Object[]{
                
                    adocao.getIdadocao(),
                    adocao.getIdanimal(),
                    adocao.getIdcliente(),
                    adocao.getIdfuncionario(),
                    adocao.getData()
                    
                });
                
                
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbanimal = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbcliente = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbfuncionario = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txdata = new javax.swing.JFormattedTextField();
        btatualiza = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btguarda = new javax.swing.JButton();
        ptabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbadocao = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tela de Adoção");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Pedido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 70, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Animal:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        cbanimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Animal" }));
        getContentPane().add(cbanimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 170, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tutor:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        cbcliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Cliente" }));
        getContentPane().add(cbcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 170, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Funcionário:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        cbfuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Funcionario" }));
        getContentPane().add(cbfuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 170, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        try {
            txdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 80, 30));

        btatualiza.setBackground(new java.awt.Color(204, 204, 204));
        btatualiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/atualizar.png"))); // NOI18N
        btatualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btatualizaActionPerformed(evt);
            }
        });
        getContentPane().add(btatualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, -1, 30));

        jPanel1.setBackground(new java.awt.Color(200, 162, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btguarda.setBackground(new java.awt.Color(51, 255, 0));
        btguarda.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btguarda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/Gnome-Media-Floppy-32.png"))); // NOI18N
        btguarda.setText("ADOTAR");
        btguarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardaActionPerformed(evt);
            }
        });
        jPanel1.add(btguarda, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        tbadocao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Adoção", "ID Animal", "ID Cliente", "ID Funcionario", "Data"
            }
        ));
        jScrollPane1.setViewportView(tbadocao);

        javax.swing.GroupLayout ptabelaLayout = new javax.swing.GroupLayout(ptabela);
        ptabela.setLayout(ptabelaLayout);
        ptabelaLayout.setHorizontalGroup(
            ptabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ptabelaLayout.setVerticalGroup(
            ptabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(ptabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 720, 280));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo_2.PNG"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setPreferredSize(new java.awt.Dimension(970, 700));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1060, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btguardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardaActionPerformed
        
        passadados();
        adocaodao.insertAdocao(adocao);
        ptabela.setVisible(true);
        btatualiza.setVisible(true);
        
    }//GEN-LAST:event_btguardaActionPerformed

    private void btatualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btatualizaActionPerformed
        
        mostratabela();
        
    }//GEN-LAST:event_btatualizaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelAdocao().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btatualiza;
    private javax.swing.JButton btguarda;
    private javax.swing.JComboBox<String> cbanimal;
    private javax.swing.JComboBox<String> cbcliente;
    private javax.swing.JComboBox<String> cbfuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel ptabela;
    private javax.swing.JTable tbadocao;
    private javax.swing.JFormattedTextField txdata;
    // End of variables declaration//GEN-END:variables
}
